Repository octokit/plugin-request-log.js, pull requests merged in 2023-06, with the labels that each got.

#326 fix(build): switch to esbuild
  package-lock.json
  package.json
  scripts/build.mjs
  test/tsconfig.test.json
  tsconfig.json
Labels: Type: Maintenance

#321 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package.json
  scripts/build.mjs
Labels: Type: Breaking change, Type: Maintenance

#329 docs: replace references to Skypack CDN with esm.sh
  README.md
Labels: Type: Documentation
